import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export class SeedService {
  async seed() {
    try {
      const currentDate = new Date();

      await prisma.users.createMany({
        data: [
          {
            name: 'Marcos Camargo',
            email: 'marcos.camargo@gmail.com',
            password: '123456',
            deleted: false,
          },
          {
            name: 'Lucas Henrique',
            email: 'lucas.henrique@gmail.com',
            password: '123456',
            deleted: false,
          },
          {
            name: 'Ana Beatriz',
            email: '123456',
            password: 'ana.beatriz@gmail.com',
            deleted: false,
          },
        ].map((user) => ({
          name: user.name,
          email: user.email,
          password: user.password,
          deleted: user.deleted,
        })),
      });

      await prisma.categories.createMany({
        data: [
          { name: 'Eletrônicos' },
          { name: 'Roupas' },
          { name: 'Acessórios' },
          { name: 'Cosméticos' },
          { name: 'Alimentos' },
          { name: 'Livros' },
          { name: 'Esportes' },
          { name: 'Móveis' },
          { name: 'Jogos' },
          { name: 'Brinquedos' },
        ],
      });

      await prisma.products.createMany({
        data: [
          {
            name: 'iPhone 12',
            status: 'Ativo',
            created_by: 1,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'MacBook Pro',
            status: 'Ativo',
            created_by: 2,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'Camiseta Polo',
            status: 'Ativo',
            created_by: 3,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Calça Jeans',
            status: 'Ativo',
            created_by: 2,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Bolsa de Couro',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Óculos de Sol',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Perfume Importado',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Maquiagem',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Arroz',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Feijão',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Livro de Romance',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Livro de Ficção Científica',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Bola de Futebol',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Raquete de Tênis',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Sofá',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'Mesa de Jantar',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'PlayStation 5',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'Nintendo Switch',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'Carrinho de Controle Remoto',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
          {
            name: 'Boneca',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
          {
            name: 'Smart TV 4K',
            status: 'Ativo',
            created_by: 2,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'Notebook Dell',
            status: 'Ativo',
            created_by: 2,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'Vestido Floral',
            status: 'Ativo',
            created_by: 2,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Camisa Social',
            status: 'Ativo',
            created_by: 2,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Colar de Prata',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Relógio de Pulso',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Batom Vermelho',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Shampoo Anti-Caspa',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Chocolate',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Café',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Livro de Suspense',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Livro de Fantasia',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Bola de Basquete',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Raquete de Pingue-Pongue',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Poltrona',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'Cama King Size',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'Xbox Series X',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'PlayStation 4',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'Quebra-Cabeça',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
          {
            name: 'Carrinho de Bonecas',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
          {
            name: 'Fone de Ouvido Bluetooth',
            status: 'Ativo',
            created_by: 2,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'Jaqueta de Couro',
            status: 'Ativo',
            created_by: 2,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Óculos de Sol',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Perfume Feminino',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Café em Grãos',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Agenda 2023',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Bola de Futebol',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Mesa de Jantar',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'Nintendo Switch',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'Boneca Barbie',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
          {
            name: 'Smartphone Samsung',
            status: 'Ativo',
            created_by: 2,
            categories_id: 1,
            created: currentDate,
          },
          {
            name: 'Vestido de Festa',
            status: 'Ativo',
            created_by: 2,
            categories_id: 2,
            created: currentDate,
          },
          {
            name: 'Relógio de Luxo',
            status: 'Ativo',
            created_by: 2,
            categories_id: 3,
            created: currentDate,
          },
          {
            name: 'Perfume Masculino',
            status: 'Ativo',
            created_by: 2,
            categories_id: 4,
            created: currentDate,
          },
          {
            name: 'Biscoitos',
            status: 'Ativo',
            created_by: 2,
            categories_id: 5,
            created: currentDate,
          },
          {
            name: 'Livro de Romance',
            status: 'Ativo',
            created_by: 2,
            categories_id: 6,
            created: currentDate,
          },
          {
            name: 'Bola de Tênis',
            status: 'Ativo',
            created_by: 2,
            categories_id: 7,
            created: currentDate,
          },
          {
            name: 'Sofá de Couro',
            status: 'Ativo',
            created_by: 2,
            categories_id: 8,
            created: currentDate,
          },
          {
            name: 'PlayStation 5',
            status: 'Ativo',
            created_by: 2,
            categories_id: 9,
            created: currentDate,
          },
          {
            name: 'Quebra-Cabeça 3D',
            status: 'Ativo',
            created_by: 2,
            categories_id: 10,
            created: currentDate,
          },
        ],
      });

      // Continue criando e populando outros modelos de acordo com suas necessidades

      await prisma.$disconnect();
    } catch (error) {
      console.error(error);
      process.exit(1);
    }
  }
}

export default SeedService;
